[gcp_service_account]

type: "service_account"
service_account = true
project_id = "datafest-hackathon"
private_key_id = "4c1d9293ad9bb43e8db11dd80b40615833862bca"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQD1p0iQa4Sa+fuw
ZrwqhPnQNww55eLWTnqltsmDMr0wo/fcs3Kmr+D620+xVuZbMILyRlBwz/4Eh3D8
v2aMt3v/6gWrEguLamUhEw2cEHOY7Fs+NUdKlsgL8UCTl9XE4Y0PYZ7Cn61UMBus
CIYXBo6p0EJ1/RQjUeb8sPBXOY1jOzzwEMRbrs45onhQ3cY3H+oAOcOWmTPq1KGy
JsIb1SeVirFosmoNTU70q4y++wpJbqkJviUFB5+Flc/IFGzM3GKOYuSuG4jq+6kR
l3a+VHr6wEzGLNJ6tHZA35OT5hhlhdSkUuOIk2DHyS6LJmSLte2JXJmXJJvakV6a
wknDFzD1AgMBAAECggEAC7EKRST4Evf8xWMvJ5C1vHXxc3j9DPxmHg7fNBewXu+f
rp9tmibXsADLoAuPggp2FQNWAhFRv1Pvg5Jor+y7FPQSduQKBh9KdskSHJn0DBsM
GnlNLkZ5kqEirm04NW5gH3nV/uCijnwneQGpcun/1LyB4t01PegaQW96nnm+ZuXo
cnzZ2QABOPx/BKyAHIfYaMLFhJNvGi95srVipt8UhkQ+tC7WuipbOFpBifdtoXC7
YBUz+PFiNp735yUiMUz5d+dg9iLxl4mf5m+NA680cDaVGKVNOJ43QzW7ZgkyVzFi
P/iyb7DfmKoJeRkW8nza5Vjh645sPn1ivEB1X45JCQKBgQD8yTsJu11Ci1h+8apL
fIKtGH+q+BeBL6fBLs8LDcNfUI5NF0jMcbEoxYJMc4tb8/7O4ckWncawmtTyoO2Y
yIzRLZoDBlwsLLK/BdfZa6TEdX5dGjwKcgvuLHgVfxSEYV4BLvOotBI+jYsI7DZN
lHv2Vt0LKvHtCu1axWdwS4vMSQKBgQD4xtZsecOliv7pzQW1STRMpG2Z5tq5qSIc
PDoo1DipMlhrW462TKLNaq/fhh4UWpYE7Gb8gexIMTYDirIf5Sy+ErM3hPsOY53g
vOZ324rnue9Q5dsiESZgbYUwrihBBSaYcnVo2Yr+8vzf9T3I/UqepMqsPazUM+t/
wedoIE7HTQKBgQDku509OBmyDe6cp0XFmjuQLxvOc0Cpd5qe1iEoSmLfiz/IB+qq
e7GnR9iYHvEZ2lVVk75mRYu039USWoXDeqzY1h+G3ylmG2f+K2Zd6OYlkn8t9YAg
n4OmFvztzpidFJGAFqEJpS7hBSiqgTq9xj7I716CLXDNYdbWDMuFNAaiaQKBgQCb
6IEZGnZymNmIzOR26JnOLn5BpVwOXuDxsQ0B6X5ZCyQ+o/KcbQrakbIG85aGSv8Z
ts4UEZhy5eRj89gOBSI1PKL0eHKeYe/fmIMXOo+jCfPhTyw1/Wl/pSODjqHLnd7C
S3kpbKyfesjf0mIWRCcvpTcfGsfldWRxfKP5rcWxQQKBgQCTfY6IMGT4+eJhn0Ga
lIY1wvBoQnnaV3qfkeIQ7kAp2Uo/DfFeihVN3ea6BoBWfs93Bd+5K5vRLjsLiRXH
A6BqxsnY7tZetuwAlHOb+0+ILTmgtv7EdXba+x8WPUhCass9H/QhS/5dZR2CKOlc
duxZyi4nOUilRSgw5VQkx42eRQ==
-----END PRIVATE KEY-----
"""
email = "datafesthackathon@datafest-hackathon.iam.gserviceaccount.com"
id = "117182881286517620862"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/datafesthackathon%40datafest-hackathon.iam.gserviceaccount.com"
domain = "googleapis.com"
